import './accounts'
import './deploy-test-token'
import './deploy-test-weth'
import './add-liquidity'
import './set-in-private-mode'
import './set-prices-with-bits'
import './set-fees'
import './gen-account'
import './gen-accounts'
import './set-spread'
import './set-max-global-sizes'
import './contracts-address'

import './stake/index'
import './uniswap/index'